services:
  gameoflife-api:
    container_name: gameoflife-api
    networks:
      - gameoflife_network
    build:
      context: .
      dockerfile: Dockerfile
    image: gameoflife-api:1.0.0
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
    depends_on:
      db:
        condition: service_healthy
        restart: true
      migrate:
        condition: service_completed_successfully

  db:
    image: postgres
    container_name: gameoflife-db
    networks:
      - gameoflife_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  
  migrate:
    image: postgres
    networks:
      - gameoflife_network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./sql:/migrations
    entrypoint: >
      bash -c "
        echo 'Waiting for database...';
        until pg_isready -h ${DB_HOST} -p ${DB_PORT} -U ${DB_USER}; do
          sleep 2;
        done;
        echo 'Database ready, applying migrations...';
        PGPASSWORD=${DB_PASSWORD} psql -h ${DB_HOST} -U ${DB_USER} -d ${DB_NAME} -v ON_ERROR_STOP=1 -f /migrations/migrate.sql;
        echo 'Migrations applied successfully. Exiting.';
      "
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

networks:
  gameoflife_network:
    driver: bridge

volumes:
  pgdata:
